name: Run maven tests using couchbase service container
on:
  workflow_dispatch
jobs:
  tests:
    runs-on: alpine-latest
    container: alpine-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    services:
      couchbase:
        image: couchbase:7.0.0-beta
