name: Run maven tests using couchbase service container
on:
  workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup couchbase
      run: |
        printf "Waiting for CB startup..."
        wget -O /dev/null  http://localhost:8091/ && echo "DONE" || (echo "FAIL" && panic)
        curl  -u Administrator:password -v -X POST \
          http://localhost:8091/nodes/self/controller/settings \
          -d 'path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fdata&' \
          -d 'index_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fidata&' \
          -d 'cbas_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fadata&' \
          -d 'eventing_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fedata&'
        curl  -v -X POST http://localhost:8091/node/controller/setupServices -d 'services=kv%2Cn1ql%2Cindex' || echo "FAILED TO SETUP SERVICES"
        curl  -v -X POST http://localhost:8091/pools/default -d 'memoryQuota=256' -d 'indexMemoryQuota=256' || echo "FAILED TO SETUP QUOTAS"
        curl  -u Administrator:password -v -X POST http://localhost:8091/settings/web -d 'password=password&username=Administrator&port=SAME' || echo "FAILED TO SETUP LOGIN"
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    services:
      couchbase:
        image: couchbase:enterprise-7.0.0-beta
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 8095:8095
          - 8096:8096
          - 9140:9140
          - 11210:11210
          - 11211:11211
          - 11207:11207
          - 18091:18091
          - 18092:18092
          - 18093:18093
          - 18094:18094
          - 18095:18095
          - 18096:18096
