name: Run maven tests using couchbase service container
on:
  workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    container: java:9-jdk
    steps:
    - name: Setup couchbase
      run: |
        printf "Waiting for CB startup..."
        wget -O /dev/null  http://couchbase:8091/ && echo "DONE" || (echo "FAIL" && panic)
        curl  -v -X POST http://couchbase:8091/node/controller/setupServices -d 'services=kv%2Cn1ql%2Cindex'
        curl  -v -X POST http://couchbase:8091/pools/default -d 'memoryQuota=256' -d 'indexMemoryQuota=256'
        curl  -u Administrator:password -v -X POST http://couchbase:8091/settings/web -d 'password=password&username=Administrator&port=SAME'
        curl  -u Administrator:password -v -X POST http://couchbase:8091/settings/indexes -d 'storageMode=memory_optimized'
        curl  -u Administrator:password -v -X GET http://couchbase:8091/pools/default | jq '.' | grep hostname
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    services:
      couchbase:
        image: couchbase:enterprise-7.0.0-beta
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 8095:8095
          - 8096:8096
          - 9140:9140
          - 11210:11210
          - 11211:11211
          - 11207:11207
          - 18091:18091
          - 18092:18092
          - 18093:18093
          - 18094:18094
          - 18095:18095
          - 18096:18096
